sudo: true
language: php
php:
  - 7.3
  - 7.4

matrix:
    fast_finish: true

branches:
  only:
    - /main/
    - /^dev/

before_install:
  - export SCRIPT_DIR=$HOME/islandora_ci

install:
  - git clone https://github.com/Islandora/islandora_ci.git $HOME/islandora_ci
  - composer install
  - php -r 'require("vendor/autoload.php"); use Islandora\Chullo\FedoraApi; $chullo = FedoraApi::create("http://future.islandora.ca:8080/fcrepo/rest"); echo $chullo->getResource("http://future.islandora.ca:8080/fcrepo/rest");' 

script:
  - $SCRIPT_DIR/line_endings.sh $TRAVIS_BUILD_DIR
  - composer test

notifications:
  irc:
    channels:
      - "irc.freenode.org#islandora"
    on_success: change
    on_failure: always
    skip_join: true

after_success:
  - bash <(curl -s https://codecov.io/bash)
